name: Update ghcr.io image

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ !startsWith(github.event.head_commit.message, 'v ') }}
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          tags:
            ghcr.io/chemical118/krcli:latest